# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grolsch_article_no', models.CharField(max_length=255)),
                ('grolsch_name', models.CharField(max_length=255)),
                ('price_track_id', models.CharField(max_length=255, null=True)),
                ('last_price', models.PositiveIntegerField(null=True)),
                ('last_discount_price', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnresolvedPriceChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grolsch.Product')),
            ],
        ),
    ]
