# Generated by Django 5.2.13 on 2026-05-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grolsch', '0002_auto_20180709_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_track_id',
        ),
    ]
