# Generated by Django 5.2.13 on 2026-05-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grolsch', '0003_remove_product_price_track_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='grolsch_article_no',
            new_name='grolsch_id',
        ),
    ]
