# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Instellingen',
                'ordering': ['key'],
                'verbose_name': 'Instelling',
            },
        ),
    ]
