# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alexia_name', models.CharField(max_length=100, unique=True)),
                ('multivers_id', models.CharField(max_length=50, null=True)),
                ('vat_type', models.CharField(choices=[('0', 'Exclusief'), ('1', 'Inclusief')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alexia_id', models.IntegerField()),
                ('alexia_name', models.CharField(max_length=20)),
                ('multivers_id', models.CharField(max_length=20)),
            ],
        ),
    ]
