# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0002_costumer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='vat_type',
            field=models.CharField(choices=[('0', 'Exclusief BTW'), ('1', 'Inclusief BTW')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='alexia_id',
            field=models.IntegerField(unique=True),
        ),
    ]
