# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0004_auto_20170202_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='multivers_name',
            field=models.CharField(default='pudding', max_length=100),
            preserve_default=False,
        ),
    ]
