# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0005_product_multivers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('no_discount', models.IntegerField(choices=[(0, 'No discount'), (1, 'Discount if exclusive'), (2, 'Always discount')])),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('alexia_name',)},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['key'], 'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
    ]
