# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0008_product_margin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Customer',
        ),
    ]
