# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-04 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0009_auto_20180704_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multivers.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptOrderDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('locations', models.ManyToManyField(to='multivers.Location')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multivers.ConceptOrder')),
            ],
        ),
        migrations.CreateModel(
            name='ConceptOrderDrinkLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multivers.ConceptOrderDrink')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multivers.Product')),
            ],
        ),
    ]
