# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0010_conceptorder_conceptorderdrink_conceptorderdrinkline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptorder',
            options={'ordering': ['date', 'customer']},
        ),
        migrations.AlterModelOptions(
            name='conceptorderdrink',
            options={'ordering': ['date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='conceptorderdrinkline',
            options={'ordering': ['product']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['multivers_id']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('multivers_id',)},
        ),
    ]
