# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-14 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0011_auto_20180709_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptorderdrink',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
