# Generated by Django 2.2.23 on 2021-05-24 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0012_conceptorderdrink_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multivers.Customer'),
        ),
        migrations.AlterField(
            model_name='conceptorderdrink',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multivers.ConceptOrder'),
        ),
        migrations.AlterField(
            model_name='conceptorderdrinkline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='multivers.Product'),
        ),
    ]
