# Generated by Django 5.2.13 on 2026-04-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0013_auto_20210525_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptorderdrink',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multivers.conceptorder'),
        ),
    ]
