# Generated by Django 2.2.23 on 2024-01-10 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0013_auto_20210525_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='moneybird_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='moneybird_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='product',
            name='moneybird_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='conceptorderdrink',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multivers.ConceptOrder'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='multivers_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='multivers_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='multivers_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
