# Generated by Django 5.2.13 on 2026-04-18 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multivers', '0014_auto_20240110_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='moneybird_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moneybird_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='moneybird_name',
        ),
    ]
