# Generated by Django 5.2.13 on 2026-04-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['date', 'customer'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alexia_name', models.CharField(max_length=100, unique=True)),
                ('moneybird_id', models.CharField(blank=True, max_length=50, null=True)),
                ('vat_type', models.CharField(choices=[('0', 'Exclusief BTW'), ('1', 'Inclusief BTW')], max_length=1, null=True)),
            ],
            options={
                'ordering': ['moneybird_id'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('no_discount', models.IntegerField(choices=[(0, 'No discount'), (1, 'Discount if exclusive'), (2, 'Always discount')], null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alexia_id', models.IntegerField(unique=True)),
                ('alexia_name', models.CharField(max_length=100)),
                ('moneybird_id', models.CharField(blank=True, max_length=20)),
                ('moneybird_name', models.CharField(blank=True, max_length=100)),
                ('margin', models.IntegerField(choices=[(0, 'No margin'), (1, 'Has margin')], default=1)),
            ],
            options={
                'ordering': ('moneybird_id',),
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='ConceptOrderDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('sent', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneybird.conceptorder')),
                ('locations', models.ManyToManyField(to='moneybird.location')),
            ],
            options={
                'ordering': ['date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='conceptorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneybird.customer'),
        ),
        migrations.CreateModel(
            name='ConceptOrderDrinkLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneybird.conceptorderdrink')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneybird.product')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
    ]
