# Generated by Django 5.2.13 on 2026-04-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptorderdrink',
            name='locations',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['moneybird_id']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='margin',
        ),
        migrations.AddField(
            model_name='conceptorderdrink',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
