# Generated by Django 5.2.13 on 2026-04-14 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0002_remove_conceptorderdrink_locations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conceptorderdrink',
            old_name='location',
            new_name='locations',
        ),
    ]
