# Generated by Django 5.2.13 on 2026-04-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0003_rename_location_conceptorderdrink_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptorderdrink',
            name='locations',
            field=models.CharField(max_length=255),
        ),
    ]
