# Generated by Django 5.2.13 on 2026-04-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0004_alter_conceptorderdrink_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptorderdrink',
            name='sent',
        ),
        migrations.AddField(
            model_name='conceptorder',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
