# Generated by Django 5.2.13 on 2026-04-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0005_remove_conceptorderdrink_sent_conceptorder_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['alexia_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['alexia_id']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='moneybird_name',
        ),
        migrations.AddField(
            model_name='product',
            name='ledger_account_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate_id',
            field=models.CharField(choices=[('0', '21%'), ('1', '9%'), ('2', '0%'), ('3', 'BTW vrijgesteld')], default='0', max_length=1),
        ),
    ]
