# Generated by Django 5.2.13 on 2026-04-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0006_alter_customer_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='moneybird_id',
            field=models.CharField(blank=True, default='', max_length=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='ledger_account_id',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='product',
            name='moneybird_id',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
