# Generated by Django 5.2.13 on 2026-04-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0007_alter_customer_moneybird_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat_rate_id',
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
