# Generated by Django 5.2.13 on 2026-04-17 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0008_alter_product_vat_rate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(choices=[('0', '21%'), ('1', '9%'), ('2', '0%'), ('3', 'BTW vrijgesteld')])),
                ('moneybird_id', models.CharField(blank=True, max_length=18)),
            ],
            options={
                'ordering': ['rate'],
            },
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_type',
            field=models.CharField(choices=[('0', 'Exclusief BTW'), ('1', 'Inclusief BTW')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneybird.taxrate'),
        ),
    ]
