# Generated by Django 5.2.13 on 2026-04-18 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0008_alter_product_vat_rate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('0', 'Bier'), ('1', 'Speciaalbier'), ('2', 'Wijn'), ('3', 'Fris'), ('4', 'Maltbier'), ('5', 'Snacks'), ('6', 'Speciaalbier van de maand'), ('7', 'Likeur')], max_length=1, unique=True)),
                ('ledger_account_id', models.CharField(blank=True, max_length=18)),
            ],
            options={
                'ordering': ['product_type'],
            },
        ),
        migrations.CreateModel(
            name='VatRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_rate', models.CharField(choices=[('0', '21%'), ('1', '9%'), ('2', '0%'), ('3', 'BTW vrijgesteld')], max_length=1, unique=True)),
                ('moneybird_id', models.CharField(max_length=18)),
            ],
            options={
                'ordering': ['vat_rate'],
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='vat_rate_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ledger_account_id',
        ),
        migrations.AddField(
            model_name='producttype',
            name='vat_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneybird.vatrate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='vat_type',
            field=models.CharField(choices=[('0', 'Exclusief BTW'), ('1', 'Inclusief BTW')], default='1', max_length=1),
        ),
    ]
