# Generated by Django 5.2.13 on 2026-04-18 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0009_producttype_vatrate_remove_product_vat_rate_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='moneybird.producttype'),
            preserve_default=False,
        ),
    ]
