# Generated by Django 5.2.13 on 2026-04-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0010_remove_product_id_product_product_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='product_type',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vatrate',
            name='vat_rate',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
