# Generated by Django 5.2.13 on 2026-04-19 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0011_alter_producttype_product_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='product_type',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='moneybird.producttype'),
        ),
    ]
