# Generated by Django 5.2.13 on 2026-04-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0012_alter_producttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='vat_type',
            field=models.CharField(blank=True, choices=[('0', 'Exclusief BTW'), ('1', 'Inclusief BTW')], max_length=1),
        ),
    ]
