# Generated by Django 5.2.13 on 2026-04-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneybird', '0013_alter_customer_vat_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptorder',
            name='sent',
        ),
    ]
