# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-13 16:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('O', 'Organization'), ('F', 'Function'), ('P', 'Person')], max_length=1)),
                ('outgoing_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('incoming_aliases', models.CharField(blank=True, max_length=255, validators=[django.core.validators.RegexValidator('[a-z0-9-_,]*')])),
                ('group_destinations', models.ManyToManyField(blank=True, related_name='group_origins', to='mail.Group')),
            ],
            options={
                'ordering': ('type', 'name'),
            },
        ),
    ]
